### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by sympapa** [sckzw/AANotifier#1]
I am very interested in this app.
But I can't install "aanotifier-v0.2.1-release-unsigned.apk"
I also tried to install from adb, but I got "Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates...".
Do I need to sign it myself?
If possible, please upload the signed apk.

**Comment by sckzw** [comment]
Please try installing ["aanotifier-v0.2.1-release-signed.apk"](https://github.com/sckzw/AANotifier/releases/tag/v0.2.1)

**Comment by sympapa** [comment]
Thank you for your quick response. 
 I was able to install it , the notifications on car device  seem to be working fine.

ありがとうございました！
また何かあれば書き込みさせてください。
