### ISSUE TITLE
Android 11

### ISSUE THREAD

**Issue by Squire298** [sckzw/AANotifier#3]
this doesn't seem to work with Android 11 set on developer mode and a locked screen, is there a work around?

**Comment by sckzw** [comment]
Hi,

Does it work correctly when the device screen is displayed and unlocked?
Are notifications displayed on the device's lock screen when it is not working?

Notification may be delayed when the screen is off.
When notifications are delayed, notifications to the Android Auto head unit will also be delayed.

On Google Pixel 5a (Android 12) it works fine with the lock screen and with the screen off. Notifications are delayed by a few minutes though.

Thank you

Translated with www.DeepL.com/Translator (free version)

**Comment by Squire298** [comment]
I have not been able to get anything out of the app at all, no display on the phone or on the head unit in the car, im running an android samsung A32

**Comment by sckzw** [comment]
> no display on the phone

If notifications do not appear on the phone, then notifications will not appear on the Androidauto unit either.
Please check the "Adaptive Notifications" setting or "Battery optimization" setting on your phone.
- [ ] Disable "Adaptive Notifications"
- [ ] Disable "Battery optimization"

If you see notifications on your phone but not on your Androidauto unit, please recheck the following settings.
- [ ] Enable "Unknown sources" in Android Auto app
- [ ] Enable "General settings -> Android Auto notification" in this app
- [ ] Select apps in "General settings -> Application list" in this app
- [ ] Allow AANotifier on the "notification access" setting
- [ ] Disable "Test settings -> Car mode" in this app

**Comment by Squire298** [comment]
Everything listed here is not really the same on this Samsung A32 but the items I did change made no difference.

The AAnotify app doesn't even pop up on the phone, I suspect that it's not really working...

**Comment by Squire298** [comment]
Under running apps AAnotify doesn't seem to be running as it seems it should be because it's a service

**Comment by sckzw** [comment]
If the NotificationListenerService is not working, the app will not work properly. The figure below shows the screen when the service is running.
<img src="https://user-images.githubusercontent.com/4351207/172604208-e61395d3-168f-4db2-997b-e28ec3966167.png" width="240">

Please try installing this APK file. I simply renamed NotificationListenerService.
[aanotifier-rename-v0.2.2-release-signed.zip](https://github.com/sckzw/AANotifier/files/8861089/aanotifier-rename-v0.2.2-release-signed.zip)

The following are reference sites.
https://issuetracker.google.com/issues/36984668
https://stackoverflow.com/questions/33530807/why-is-this-notificationlistenerservice-not-working

**Comment by Squire298** [comment]
App is running, app has access to notify but still isn't pushing the notifications even though the apps are in the app list.

![Screenshot_20220609-070505_AANotifier](https://user-images.githubusercontent.com/23255124/172696586-ec89dd9c-c809-4014-a432-c22b7866af0b.jpg)

![Screenshot_20220609-070515_Settings](https://user-images.githubusercontent.com/23255124/172696627-5e55b5a0-5916-43e0-ab49-8372d6d36649.jpg)

**Comment by sckzw** [comment]
Please try the following steps.

Configure as follows.
- Disable "Test settings -> Car mode"
- Enable "Test settings -> Sprious notification"

Notify from the application you have selected in the application list of AANotifier. (For example: Gmail)

Confirm that the AANotifier notification is displayed as shown below. This notification is called "Spurious notification". Normally, it is not displayed, but it is displayed by the above setting.

The following figure shows the Pixel 4 (Android 11) emulator screen.
<img src="https://user-images.githubusercontent.com/4351207/172870056-ca17b306-1a23-4b17-a913-4c346d7b0b71.png" width="240" />
<img src="https://user-images.githubusercontent.com/4351207/172870084-2089676c-1792-4226-bb29-a255a8d4a839.png" width="240" />
<img src="https://user-images.githubusercontent.com/4351207/172870103-2caa4b74-ad08-4747-975d-96a5658d967f.png" width="240" />

**Comment by Squire298** [comment]
no this is not working, i have tried every setting on the app. it simply isnt working.

**Comment by Squire298** [comment]
OK, I am getting the notification to AAnotify but it's not passing it on to Android auto

**Comment by sckzw** [comment]
AANotifier seems to be sending notifications (AANotifier service is working).
However, Android Auto app or head unit (Car infotainment system) does not seem to handle notifications.

Is the Android Auto App settings screen as shown below?
If the settings are correct, the cause seems to be a problem that depends on the Android Auto app or head unit (e.g. head unit is restricting apps of unknown source). I am not able to analyze them and therefore cannot solve this problem.
<img src="https://user-images.githubusercontent.com/4351207/173178388-8cbb2ba8-8184-4e9f-9526-0d834dae4310.png" width="240" />
<img src="https://user-images.githubusercontent.com/4351207/173178391-64a4d67f-97ad-47bc-a9ea-0bb6a46f33fe.png" width="240" />

**Comment by Squire298** [comment]
Yes everything you have said shows on my android auto app. Yes it seems the head unit can't do notifications
