### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by gilder69** [sckzw/AANotifier#4]
AANotifier doesn't  work for the past few days.
I think It might be because Android Auto has been updated...

Android 12
Android Auto: 11.2.640434-release
AANotifier: 0.2.2

thank you

**Comment by sckzw** [comment]
Thank you for the information.
I will check.

**Comment by sckzw** [comment]
I checked and the app worked as expected.
Android 14
Android Auto: 11.2.640434-release
AANotifier: 0.2.2

Please configure AANotifier as follows.
Disable "Car mode"
Enable "Spurious notification"

As shown in the figure below, when notifications from apps enabled in AANotifier's application list are displayed, is AANotifier notification also displayed?

![Screen shot 2024-03-09 160630](https://github.com/sckzw/AANotifier/assets/4351207/702e2c65-a3d8-45af-86b9-3a79ccce2093)

**Comment by gilder69** [comment]
Thanks for your reply :)
AANotifier notification popped up on my screen, so I tested it in my car and it worked properly...
It had not work even though turning on/off or reinstalling it, but for some reason it seems to have been fixed. I don't know why.
I apologized for the inconvenience.
